name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Build / ubuntu-latest (x86_64) / ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use_cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Generate SVGs
        run: |
          mkdir -p artifacts
          for name in fossable sandpolis goldboot gantry turbine; do
            target/${{ matrix.target }}/release/fossable emblem ${name} --output artifacts --icon --bg
            target/${{ matrix.target }}/release/fossable emblem ${name} --output artifacts --icon
            target/${{ matrix.target }}/release/fossable emblem ${name} --output artifacts
          done

      - name: Generate PNGs
        run: ./raster.sh

      - uses: actions/upload-artifact@v4
        with:
          name: fossable-assets
          path: artifacts

