name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Build / ubuntu-latest (x86_64) / ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Generate SVGs
        run: |
          mkdir -p artifacts
          for name in fossable sandpolis goldboot gantry turbine outpost; do
            target/release/fossable emblem ${name} --output artifacts --icon --bg
            target/release/fossable emblem ${name} --output artifacts --icon
            target/release/fossable emblem ${name} --output artifacts
          done

      - name: Generate PNGs
        run: ./raster.sh artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: fossable-assets
          path: artifacts

  dist-archlinux:
    name: Dist / ArchLinux (x86_64) / ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - goldboot
          - goldboot-registry
          - sandpolis
          - sandpolis-agent
          - sandpolis-agent-git
          - sandpolis-client
          - sandpolis-client-git
          - sandpolis-server
          - sandpolis-server-git
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build archlinux package
        uses: heyhusen/archlinux-package-action@v2
        with:
          path: dist/pacman/${{ matrix.package }}
          flags: "-si --noconfirm"
          namcap: true
          updpkgsums: true
          srcinfo: true
