name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    name: Build / ubuntu-latest (x86_64) / ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use_cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Generate artifacts
        run: |
          mkdir artifacts
          for name in fossable sandpolis goldboot gantry turbine; do
            # Generate SVG
            target/${{ matrix.target }}/release/fossable ${name} --output artifacts --icon --bg
            target/${{ matrix.target }}/release/fossable ${name} --output artifacts --icon
            target/${{ matrix.target }}/release/fossable ${name} --output artifacts

            # Generate emblem rasters
            for height in 256 512 1024 2048 4096; do
              for file in ${name}-bg-icon ${name}-nobg-icon ${name}-nobg-noicon; do
              	inkscape --export-type png -h ${height} -o artifacts/${file}-${height}.png artifacts/${file}.svg
              done
            done

            # Generate icon rasters
            for height in 32 64 128 256 512 1024 2048; do
            	inkscape --export-type png -h ${height} -o artifacts/${name}-${height}.png icons/${name}.svg
            done
          done

      - uses: actions/upload-artifact@v4
        with:
          path: artifacts

