name: dist
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dist-archlinux:
    name: Dist / ArchLinux (x86_64) / ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - goldboot
          - goldboot-registry
          - sandpolis
          - sandpolis-agent
          - sandpolis-agent-git
          - sandpolis-client
          - sandpolis-client-git
          - sandpolis-server
          - sandpolis-server-git
    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodule
        id: checkout_submodule
        env:
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
        run: |
          echo "${AUR_PRIVATE_KEY}" >/tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh-keyscan -H aur.archlinux.org >/tmp/known_hosts

          GIT_SSH_COMMAND='ssh -i /tmp/id_rsa -o UserKnownHostsFile=/tmp/known_hosts' git submodule update --init "dist/pacman/${{ matrix.package }}"

          echo "pkgver=0.1.0" >>"$GITHUB_OUTPUT"

      - uses: heyhusen/archlinux-package-action@v2
        with:
          path: dist/pacman/${{ matrix.package }}
          flags: "-si --noconfirm"
          aur: true
          namcap: true
          srcinfo: true
          pkgver: ${{ steps.checkout_submodule.outputs.pkgver }}

      - name: Push release to AUR
        run: |
          cd "dist/pacman/${{ matrix.package }}"

          git config --global user.name "github-actions"
          git config --global user.email "10459406+cilki@users.noreply.github.com"


          git add .SRCINFO PKGBUILD
          git commit -m "release: ${{ steps.checkout_submodule.outputs.pkgver }}"
          GIT_SSH_COMMAND='ssh -i /tmp/id_rsa -o UserKnownHostsFile=/tmp/known_hosts' git push -u origin master
