name: dist
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dist-archlinux:
    name: Dist / ArchLinux (x86_64) / ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - goldboot
          - goldboot-registry
          - sandpolis
          - sandpolis-agent
          - sandpolis-agent-git
          - sandpolis-client
          - sandpolis-client-git
          - sandpolis-server
          - sandpolis-server-git
    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodule
        env:
          AUR_PRIVATE_KEY: ${{ secrets.AUR_PRIVATE_KEY }}
        run: |
          echo "${AUR_PRIVATE_KEY}" >/tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh-keyscan -H aur.archlinux.org >/tmp/known_hosts

          GIT_SSH_COMMAND='ssh -i /tmp/id_rsa -o UserKnownHostsFile=/tmp/known_hosts' git submodule update --init "dist/pacman/${{ matrix.package }}"

      - name: Query package version
        id: get_version
        run: |
          case "${{ matrix.package }}" in
          *-git)
            ;;
          sandpolis*)
            curl -s "https://crates.io/api/v1/crates/sandpolis" | jq -r '"pkgver=\(.crate.newest_version)"' >>"$GITHUB_OUTPUT"
            ;;
          *)
            curl -s "https://crates.io/api/v1/crates/${{ matrix.package }}" | jq -r '"pkgver=\(.crate.newest_version)"' >>"$GITHUB_OUTPUT"
            ;;
          esac

      - uses: cilki/archlinux-package-action@main
        with:
          path: dist/pacman/${{ matrix.package }}
          flags: "-cfsi --noconfirm"
          aur: true
          namcap: true
          srcinfo: true
          pkgver: ${{ steps.get_version.outputs.pkgver }}

      - name: Push release to AUR
        run: |
          cd "dist/pacman/${{ matrix.package }}"

          git config --global user.name "github-actions"
          git config --global user.email "10459406+cilki@users.noreply.github.com"


          git add .SRCINFO PKGBUILD
          git commit -m "release: ${{ steps.get_version.outputs.pkgver }}"
          GIT_SSH_COMMAND='ssh -i /tmp/id_rsa -o UserKnownHostsFile=/tmp/known_hosts' git push -u origin master
